In [1]:
import pandas as pd

In [2]:
file_arrive_time = "TimeMessageArrivedToMCU.csv"
df_arrive = pd.read_csv(file_arrive_time)
df_arrive.head(5)

                  data                                                 ms
0  2021-10-11 21:39:59  339  INFO --- MqttFX ClientModel             :...
1  2021-10-11 21:39:59  339  INFO --- MqttFX ClientModel             :...
2  2021-10-11 21:40:07  041  INFO --- MqttFX ClientModel             :...
3  2021-10-11 21:40:07  042  INFO --- MqttFX ClientModel             :...
4  2021-10-11 21:40:09  759  INFO --- MqttFX ClientModel             :...

In [3]:
file_depart_time = "TimeMessageDepartFromApp.csv"
df_depart = pd.read_csv(file_depart_time)
df_depart.head(5)

            data
0  1634002798332
1  1634002806036
2  1634002808768
3  1634002811844
4  1634002814211

In [4]:
import datetime
from datetime import timezone

df_time_analysis = pd.DataFrame()
df_time_analysis['time_message_arrive_to_mcu'] =  pd.to_datetime(df_arrive['data'].str.slice(stop=19) + '.' + df_arrive['ms'].str.slice(stop=4))
#df_time_analysis['time_message_arrive_to_mcu'] = df_time_analysis['time_message_arrive_to_mcu'].dt.tz_localize('UTC').dt.tz_convert('Etc/GMT+4')
df_time_analysis = df_time_analysis.iloc[::2]
df_time_analysis.reset_index(inplace=True,drop=True)
df_time_analysis.head(5)

  time_message_arrive_to_mcu
0    2021-10-11 21:39:59.339
1    2021-10-11 21:40:07.041
2    2021-10-11 21:40:09.759
3    2021-10-11 21:40:12.830
4    2021-10-11 21:40:15.221

In [5]:
import numpy as np
df_time_analysis['time_message_depart_from_app'] = pd.to_datetime(df_depart['data'],unit='ms',origin='unix')
df_time_analysis['time_message_depart_from_app'] = df_time_analysis['time_message_depart_from_app'].dt.tz_localize('UTC').dt.tz_convert('Etc/GMT+4').dt.tz_localize(None)
df_time_analysis['delta_time'] = df_time_analysis['time_message_arrive_to_mcu'] - df_time_analysis['time_message_depart_from_app']
df_time_analysis['delta_time_ms'] = (df_time_analysis['time_message_arrive_to_mcu'] - df_time_analysis['time_message_depart_from_app']).astype(np.int64) // 10**6
df_time_analysis

,time_message_arrive_to_mcu,time_message_depart_from_app,delta_time,delta_time_ms
0,2021-10-11 21:39:59.339,2021-10-11 21:39:58.332,0 days 00:00:01.007000,1007
1,2021-10-11 21:40:07.041,2021-10-11 21:40:06.036,0 days 00:00:01.005000,1005
2,2021-10-11 21:40:09.759,2021-10-11 21:40:08.768,0 days 00:00:00.991000,991
3,2021-10-11 21:40:12.830,2021-10-11 21:40:11.844,0 days 00:00:00.986000,986
4,2021-10-11 21:40:15.221,2021-10-11 21:40:14.211,0 days 00:00:01.010000,1010
5,2021-10-11 21:40:17.651,2021-10-11 21:40:16.661,0 days 00:00:00.990000,990
6,2021-10-11 21:40:20.247,2021-10-11 21:40:19.243,0 days 00:00:01.004000,1004
7,2021-10-11 21:40:22.315,2021-10-11 21:40:21.311,0 days 00:00:01.004000,1004
8,2021-10-11 21:40:24.609,2021-10-11 21:40:23.612,0 days 00:00:00.997000,997
9,2021-10-11 21:40:26.806,2021-10-11 21:40:25.816,0 days 00:00:00.990000,990
10,2021-10-11 21:40:28.952,2021-10-11 21:40:27.967,0 days 00:00:00.985000,985
11,2021-10-11 21:40:31.339,2021-10-11 21:40:30.334,0 days 00:00:01.005000,1005
12,2021-10-11 21:40:33.710,2021-10-11 21:40:32.717,0 days 00:00:00.993000,993
13,2021-10-11 21:40:35.850,2021-10-11 21:40:34.835,0 days 00:00:01.015000,1015
14,2021-10-11 21:40:38.489,2021-10-11 21:40:37.484,0 days 00:00:01.005000,1005
15,2021-10-11 21:40:40.950,2021-10-11 21:40:39.934,0 days 00:00:01.016000,1016
16,2021-10-11 21:40:43.241,2021-10-11 21:40:42.251,0 days 00:00:00.990000,990
17,2021-10-11 21:40:46.113,2021-10-11 21:40:45.129,0 days 00:00:00.984000,984
18,2021-10-11 21:40:48.036,2021-10-11 21:40:47.032,0 days 00:00:01.004000,1004
19,2021-10-11 21:41:01.529,2021-10-11 21:41:00.529,0 days 00:00:01,1000
20,2021-10-11 21:41:02.201,2021-10-11 21:41:01.207,0 days 00:00:00.994000,994
21,2021-10-11 21:41:02.715,2021-10-11 21:41:01.720,0 days 00:00:00.995000,995
22,2021-10-11 21:41:03.348,2021-10-11 21:41:02.365,0 days 00:00:00.983000,983
23,2021-10-11 21:41:03.868,2021-10-11 21:41:02.879,0 days 00:00:00.989000,989
24,2021-10-11 21:41:04.530,2021-10-11 21:41:03.522,0 days 00:00:01.008000,1008
25,2021-10-11 21:41:05.084,2021-10-11 21:41:04.089,0 days 00:00:00.995000,995
26,2021-10-11 21:41:05.616,2021-10-11 21:41:04.616,0 days 00:00:01,1000
27,2021-10-11 21:41:06.266,2021-10-11 21:41:05.268,0 days 00:00:00.998000,998
28,2021-10-11 21:41:06.841,2021-10-11 21:41:05.848,0 days 00:00:00.993000,993
29,2021-10-11 21:41:07.499,2021-10-11 21:41:06.495,0 days 00:00:01.004000,1004
30,2021-10-11 21:41:08.109,2021-10-11 21:41:07.106,0 days 00:00:01.003000,1003
31,2021-10-11 21:41:08.733,2021-10-11 21:41:07.720,0 days 00:00:01.013000,1013
32,2021-10-11 21:41:10.468,2021-10-11 21:41:08.347,0 days 00:00:02.121000,2121
33,2021-10-11 21:41:10.469,2021-10-11 21:41:08.845,0 days 00:00:01.624000,1624
34,2021-10-11 21:41:10.775,2021-10-11 21:41:09.489,0 days 00:00:01.286000,1286
35,2021-10-11 21:41:11.104,2021-10-11 21:41:10.119,0 days 00:00:00.985000,985
36,2021-10-11 21:41:11.795,2021-10-11 21:41:10.797,0 days 00:00:00.998000,998
37,2021-10-11 21:41:12.368,2021-10-11 21:41:11.376,0 days 00:00:00.992000,992
38,2021-10-11 21:41:13.003,2021-10-11 21:41:11.989,0 days 00:00:01.014000,1014
39,2021-10-11 21:41:13.621,2021-10-11 21:41:12.617,0 days 00:00:01.004000,1004
40,2021-10-11 21:41:14.153,2021-10-11 21:41:13.148,0 days 00:00:01.005000,1005
41,2021-10-11 21:41:14.827,2021-10-11 21:41:13.842,0 days 00:00:00.985000,985
42,2021-10-11 21:41:15.344,2021-10-11 21:41:14.339,0 days 00:00:01.005000,1005
43,2021-10-11 21:41:15.983,2021-10-11 21:41:14.983,0 days 00:00:01,1000
44,2021-10-11 21:41:16.510,2021-10-11 21:41:15.512,0 days 00:00:00.998000,998
45,2021-10-11 21:41:17.224,2021-10-11 21:41:16.225,0 days 00:00:00.999000,999
46,2021-10-11 21:41:17.796,2021-10-11 21:41:16.789,0 days 00:00:01.007000,1007
47,2021-10-11 21:41:18.336,2021-10-11 21:41:17.335,0 days 00:00:01.001000,1001
48,2021-10-11 21:41:18.769,2021-10-11 21:41:17.780,0 days 00:00:00.989000,989

In [6]:
analysis_file_name = "TimeAnalysis.xlsx"
df_time_analysis.to_excel(analysis_file_name,sheet_name="time_data")